// ACCEPT or REJECT JOb
export const ACCEPTREJECTJOB_REQUEST = 'ACCEPTREJECTJOB_REQUEST';
export const ACCEPTREJECTJOB_SUCCESS = 'ACCEPTREJECTJOB_SUCCESS';
export const ACCEPTREJECTJOB_FAILED = 'ACCEPTREJECTJOB_FAILED';
