export const CONFIRMPACKAGE_PICKUP_REQUEST = 'CONFIRMPACKAGE_PICKUP_REQUEST';
export const CONFIRMPACKAGE_PICKUP_SUCCESS = 'CONFIRMPACKAGE_PICKUP_SUCCESS';
export const CONFIRMPACKAGE_PICKUP_FAILED = 'CONFIRMPACKAGE_PICKUP_FAILED';
