export const CONFIRM_PICKUP_DEPARTURE_REQUEST =
  'CONFIRM_PICKUP_DEPARTURE_REQUEST';
export const CONFIRM_PICKUP_DEPARTURE_SUCCESS =
  'CONFIRM_PICKUP_DEPARTURE_SUCCESS';
export const CONFIRM_PICKUP_DEPARTURE_FAILED =
  'CONFIRM_PICKUP_DEPARTURE_FAILED';
