// confirm delivery package
export const CONFIRMPACKAGE_DELIVERY_REQUEST =
  'CONFIRMPACKAGE_DELIVERY_REQUEST';
export const CONFIRMPACKAGE_DELIVERY_SUCCESS =
  'CONFIRMPACKAGE_DELIVERY_SUCCESS';
export const CONFIRMPACKAGE_DELIVERY_FAILED = 'CONFIRMPACKAGE_DELIVERY_FAILED';
