export const GETALLPACKAGESFROMDELIVERY_REQUEST =
  'GETALLPACKAGESFROMDELIVERY_REQUEST';
export const GETALLPACKAGESFROMDELIVERY_SUCCESS =
  'GETALLPACKAGESFROMDELIVERY_SUCCESS';
export const GETALLPACKAGESFROMDELIVERY_FAILED =
  'GETALLPACKAGESFROMDELIVERY_FAILED';
