export const GET_DIRECTIONLINE_REQUEST = "GET_DIRECTIONLINE_REQUEST"
export const GET_DIRECTIONLINE_SUCCESS = "GET_DIRECTIONLINE_SUCCESS"
export const GET_DIRECTIONLINE_FAILED = "GET_DIRECTIONLINE_FAILED"