// getAllshifts
export const GETALLSHIFTS_REQUEST = 'GETALLSHIFTS_REQUEST';
export const GETALLSHIFTS_SUCCESS = 'GETALLSHIFTS_SUCCESS';
export const GETALLSHIFTS_FAILED = 'GETALLSHIFTS_FAILED';

//getsingleshift

export const GET_SINGLESHIFT_REQUEST = 'GET_SINGLESHIFT_REQUEST';
export const GET_SINGLESHIFT_SUCCESS = 'GET_SINGLESHIFT_SUCCESS';
export const GET_SINGLESHIFT_FAILED = 'GET_SINGLESHIFT_FAILED';

//get single shift delivery
export const GET_SINGLESHIFTDELIVERY_REQUEST="GET_SINGLESHIFTDELIVERY_REQUEST"
export const GET_SINGLESHIFTDELIVERY_SUCCESS="GET_SINGLESHIFTDELIVERY_SUCCESS"
export const GET_SINGLESHIFTDELIVERY_FAILED="GET_SINGLESHIFTDELIVERY_FAILED"