
// pickuop departure or done status
export const PICKUPPOINTDEPARTURE_REQUEST="PICKUPPOINTDEPARTURE_REQUEST"
export const PICKUPPOINTDEPARTURE_SUCCESS="PICKUPPOINTDEPARTURE_SUCCESS"
export const PICKUPPOINTDEPARTURE_FAILED="PICKUPPOINTDEPARTURE_FAILED"


// pickuop departure or done status
export const DELIVERY_DEPARTURE_DONE_REQUEST="DELIVERY_DEPARTURE_DONE_REQUEST"
export const DELIVERY_DEPARTURE_DONE_SUCCESS="DELIVERY_DEPARTURE_DONE_SUCCESS"
export const DELIVERY_DEPARTURE_DONE_FAILED="DELIVERY_DEPARTURE_DONE_FAILED"