export const UPLOAD_MULTIPLEPHOTOS_REQUEST = "UPLOAD_MULTIPLEPHOTOS_REQUEST"
export const UPLOAD_MULTIPLEPHOTOS_SUCCESS = "UPLOAD_MULTIPLEPHOTOS_SUCCESS"
export const UPLOAD_MULTIPLEPHOTOS_FAILED = "UPLOAD_MULTIPLEPHOTOS_FAILED"